title: gitBlog o7
author: mrschneebly
email: foo@bar.com
description: > # this means to ignore newlines until "baseurl:"
  This happens when you use github to create a blog

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
